name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Set up Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'adopt'
          java-version: '17'  # You can specify the version required for your project

      - name: Set up Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: react-app.apk
          path: android/app/build/outputs/apk/release/app-release.apk
